language: java
install: gradle assemble
script: gradle check

jdk:
  - oraclejdk8

after_success:
  - ./gradlew check jacocoTestReport coveralls

after_failure:
  - ./gradlew clean check --debug

sudo: false
